# Generated by Django 5.1.15 on 2026-07-17 10:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_agents', '0002_agentlearning'),
        ('ai_chat', '0001_initial'),
        ('organization', '0002_initial'),
        ('projects', '0001_initial'),
        ('workflow_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=50)),
                ('level', models.CharField(choices=[('organization', 'Organization'), ('project', 'Project'), ('agent', 'Agent'), ('user', 'User'), ('conversation', 'Conversation'), ('workflow', 'Workflow')], max_length=50)),
                ('type', models.CharField(choices=[('preference', 'Preference'), ('fact', 'Fact'), ('decision', 'Decision'), ('relationship', 'Relationship'), ('task', 'Task'), ('summary', 'Summary')], max_length=50)),
                ('content', models.TextField()),
                ('confidence_score', models.FloatField(default=1.0)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_memories', to='ai_agents.agent')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_memories', to='ai_chat.conversation')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_memory_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_memories', to='organization.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_memories', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_memory_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_memories', to=settings.AUTH_USER_MODEL)),
                ('workflow_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise_memories', to='workflow_engine.workflowexecution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
